sudo: false



# Jekyll

language: ruby
rvm:
- 2.3.3

script:
- set -e
- echo "Initializing Jekyll build"
- bundle exec jekyll build

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true



# Firebase

language: node_js
node_js:
- "node"

install:
- npm install -g firebase-tools

script:
- echo "Deploying!"
- firebase deploy --token $FIREBASE_TOKEN
